declare filename
Without declaring `filename`, submitting the form with text instead of
file results in the following error at line 321 (now line 322):

> UnboundLocalError: cannot access local variable 'filename' where it is not associated with a value